### ISSUE TITLE
Higher frequency ?

### ISSUE THREAD

**Issue by ok1cdj** [RPiks/pico-WSPR-tx#1]
Hello, is possible to use it higher frequencies for WSPR ? 

Regards, Ondra

**Comment by RPiks** [comment]
Hi Ondra,

I appreciate your interest in the project.

Indeed, it is a key parameter. I'm working on this issue, trying to extend upper frequency limit. Today I'm aiming to ~26...33 MHz limit in order to cover upper portion of shortwave band. The bottleneck is CPU clock value (270MHz). So, the jitter becomes an issue.

Regards, Roman
73 & 72 de R2BDY
