### ISSUE TITLE
 WSPR function needs  to comply with specification 

### ISSUE THREAD

**Issue by sivaelid** [RPiks/pico-WSPR-tx#4]
1.  On startup the beacon transmits with in a few second and transmits for 110 second. This is before the GPS  has locked so how does it know that the  time is correct to transmit?   It needs to start at 1 second past an  even minute ( 0,2,4,6...)
2.  The current version seems to only transmit on startup.  We need to have a configuration to allow it to at the correct time transmit either once continuously or every 2 minutes or say one message every set interval ( say 20 minute ) . This later setting will reduce the traffic at busy times..

 Many thanks Simon G8HAM

**Comment by RPiks** [comment]
Hi Simon,

You are right formally, but owls are definitely not what they seem :)

There is a number of key settings in main.c
Please set this define to YES from NO in order to prohibit any TX activity when GPS time hadn't been obtained.
#define CONFIG_GPS_SOLUTION_IS_MANDATORY NO

Since v.1.0 I took decision to set aforementioned option to NO because GPS receiver is an optional feature. Perhaps amateur radio guys will want to look at the spectrum, receive the signal locally etc..

Early versions of pico-hf-oscillator submodule were without GPS option. So, I manually started the Pico about ~2 sec ere WSPR tx window comes.

New version will be equipped with terminal functionality and it will be possible to set time from keyboard and terminal such as minicom.

Thank you very much for participation!

Cheers,
Roman
73!
R2BDY
